apiVersion: batch/v1
kind: Job
metadata:
  name: temp-env-var
spec:
  template:
    metadata:
     name: hook-job
     annotations:
       "helm.sh/hook": post-install
       "helm.sh/hook-delete-policy": hook-succeeded
   spec:
     containers:
       env:
         - name: SETUP
           value: "true"
     restartPolicy: OnFailure
