apiVersion: batch/v1
kind: Job
metadata:
  name: job-hook-preinstall
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: pre-install
          {{- with .Values.storagenode }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- end }}
          volumeMounts:
            - name: {{ include "storj-storagenode.fullname" . }}
              mountPath: /app/config
            - name: storj-identity
              mountPath: /app/identity
          env:
            - name: SETUP
              value: "true"
      volumes:
        - name: {{ include "storj-storagenode.fullname" . }}
          emptyDir: {} 
        - name: storj-identity
          secret:
            secretName: {{ required "External secret identity" .Values.identity.externalSecret.secretName }}
      {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "storj-storagenode.fullname" . }}
    {{- with .Values.persistence  }}
      annotations:
{{ toYaml .annotations | indent 8 }}
    spec:
{{ toYaml .volumeClaimTemplate | indent 6 }}
    {{- end }}
  {{- end }}
